### ISSUE TITLE
Multiple OTGW's

### ISSUE THREAD

**Issue by frankvandenhurk** [nlrb/com.tclcode.otgw#12]
I have two OTGW's (living room and bathroom). Is it possible to use both?

**Comment by nlrb** [comment]
Currently not. When developing it we had the discussion that it would be very unlikely that someone would have more than one...

Supporting multiple is a major rewrite, but I might consider it when going to app SDK v2.

**Comment by nlrb** [comment]
Solved in version 2.0.0.
