### ISSUE TITLE
I get a "Fout: de gateway is niet beschikbaar" error message when adding a 'boiler' 'thermostaat' or 'sensor'

### ISSUE THREAD

**Issue by 2mvent** [nlrb/com.tclcode.otgw#13]
Hi
I am trying to use an otgw together with homey.

Using: Nodo-shop version of a otgw with a NodeMCU. I can connect with the otgw using the Opentherm Monitor (otmonitor.exe) and I see all sorts of traffic between the boiler and the themostat.

I installed the Opentherm Gateway app 2.0 on my homey, added a 'gateway' and noted the ip number and port and it connected. It reads "OTG 4.2.5. Alleen monitoren: nee, Volgt thermostaat."
So far so good.

**But then when I try to connect a 'boiler' 'thermostaat' or 'sensor' I get the message:
"Fout: de gateway is niet beschikbaar"**

But I had just installed the gateway successfully?

I am stuck here. Do you know what the problem is? Or if you need more info, how could I provide this?

Best regards, Herbert

**Comment by nlrb** [comment]
Hi Herbert,

That is really strange. What Homey FW version are you using? Also, what do you see in the debug info on the app settings page? E.g. when you try to add a boiler device.

Best regards,
-Ramón.

**Comment by 2mvent** [comment]
Homey Firmware Versie: 1.5.6-rc.7
The debug info, where can I find this? I added a attachement of a screenshot, should it be visible there? I took this screenshot right after I tried to add a 'thermostat'.
![screenshot 2018-01-02 at 10 02 57](https://user-images.githubusercontent.com/31533211/34479041-a804b7be-efa4-11e7-8800-88dab1b5c290.png)

**Comment by nlrb** [comment]
Yes, you should debug info there. Since you also don't see any gateway traffic, it looks like indeed no gateway device is active.

Can you restart the app and see what shows up in the debug info?

**Comment by 2mvent** [comment]
Oh boy, I restarted the app and that debug info starts flowing rapidly since I had it on record "alles". 
And now I can add a 'thermostaat' and in general the app is working.
I just did not think of restarting the app.

Already had some fun adjusting the temperature per voice. And then resuming the program. Very neat!

Dank je voor je hulp en bedankt voor het maken van de app.

Best regards,
Herbert

**Comment by nlrb** [comment]
Ok, good to hear that it works. Still strange that this happened. But there is more strange behaviour with rc7. So I guess we'll never know :-).

**Comment by nlrb** [comment]
4f0489b was to fix #15, not this item.
