### ISSUE TITLE
Connection drops, reboot Homey resolves connection

### ISSUE THREAD

**Issue by JanSpruit** [nlrb/com.tclcode.otgw#14]
Hello,

Quite often Homey shows connection is lost with Opentherm gateway. Only way to get thermostat app working again i found is to completely reboot Homey.

Would be nice if there was some kind of connection monitoring which re initialises connection when lost for a certain period. I read something about this in old issue, but seems this can still happen in current version 2.0

Best regards,

Jan

**Comment by JanSpruit** [comment]
Hi,
I finally discovered wifi connection was bad causing only few messages being received from opentherm gateway. Placing wifidongle some where else solved problem

**Comment by nlrb** [comment]
Good to hear, that makes sense.
