### ISSUE TITLE
Homey V2 RC3 compatibility

### ISSUE THREAD

**Issue by Asinke** [nlrb/com.tclcode.otgw#15]
Testing your great app on Homey V2 RC3. Gateway and Boiler devices can be added successfully, but adding sensor device hangs the UI. Does not matter what sensor values combinations I select.

**Comment by mrmannetje** [comment]
Same issue here with Homey V2 RC11.

**Comment by nlrb** [comment]
Fixed in 2.1.0. Issue was introduced indeed when Athom moved to the app only and away from the web interface. and changed the 'list_devices' template.
