### ISSUE TITLE
App Crash in Homey V2 RC11 "de Gateway is niet beschikbaar"

### ISSUE THREAD

**Issue by mrmannetje** [nlrb/com.tclcode.otgw#16]
I have a problem that the OTGW app crashes constantly. When the app is crashed the Gateway, Boiler and Thermostat give the message "de Gateway is niet beschikbaar". After restarting the App everything works again for a period whereafter it crashes again. When the app is crashed the OTGW is still reachable.

I currently use Homey V2 RC11 with the latest iOS app installed. 

I've reinstalled the app and devices but problem stays the same. Can't find a common trigger which causes the crash. Time to crash seems random. Sometimes it works for an hour, sometimes for a day. 

Please let me know if I can support you with tests or data.

**Comment by nlrb** [comment]
Inguess this is an issue with the v2 firmware. Don’t have this myself. But SDK 2 apps that run on 1.5.13 should also work on 2.0.0.

**Comment by nlrb** [comment]
Please re-open if this is still an issue.
