### ISSUE TITLE
Homey | Remeha Gateway 16 no connection

### ISSUE THREAD

**Issue by MichaelM69** [nlrb/com.tclcode.otgw#18]
The Remeha Gateway 16 in combination with the Remeha E-Twist Thermostat doesn't connect to Opentherm Gateway App of Homey.
IP and gate is set.

**Comment by nlrb** [comment]
Can you connect with the Opentherm Monitor app?

**Comment by MichaelM69** [comment]
> Can you connect with the Opentherm Monitor app?

I use the OpenTherm Gateway app, I don't have or see the monitor app in the Athom.

**Comment by nlrb** [comment]
Download here: http://otgw.tclcode.com/otmonitor.html
