### ISSUE TITLE
Unable to add sensors

### ISSUE THREAD

**Issue by llentjes** [nlrb/com.tclcode.otgw#19]
When trying to add sensors the selection list appears (29 items, each selected) after pressing "volgende" a white screen appears and no progress is made.
I am using Homey version 2.5.2.
What can I do?

**Comment by nlrb** [comment]
Suggest you report this to Athom. The app did not change and it worked before.

**Comment by llentjes** [comment]
actually issue #17 (opened by jtebbens) is about the same problem.
Also is issue #15.
I believe your app is not working with homey v2. (Maybe when the app is already installed and then homey is upgraded. But it seems that a clean install on a homey v2 is not working.

**Comment by WillemHermsen** [comment]
I have the same issue. Can you please fix this?
if you need any help or info please let me know!

**Comment by nlrb** [comment]
Duplicate of #13 and #15.
