### ISSUE TITLE
[Request] Overrule thermostat with control setpoint

### ISSUE THREAD

**Issue by denniedegroot** [nlrb/com.tclcode.otgw#2]
My thermostat unfortunately doesn't support OpenTherm MsgID 9 (Remote override room setpoint) which means Homey cannot control the temperature. However the OTGW can overwrite this with the "CS=temperature" command. Is it possible to make a setting for this?

So instead of sending TT or TC the CS command is send.

**Comment by nlrb** [comment]
The Control Setpoint is not the same as a Room Setpoint. E.g. currently my Room Setpoint is 22 (nice and cosy), while the Control Setpoint is 30.

So sending the Room Setpoint in CS doesn't sound right. However, the next version does support sending free-format commands from a flow. So you can send any command you want, also CS.

Would that be sufficient?
![image](https://cloud.githubusercontent.com/assets/11725674/13474249/6f43d4fc-e0bd-11e5-8e51-62358736507a.png)

**Comment by denniedegroot** [comment]
You are right! The control setpoint is something totally different, I thought it was working correctly because my room temperature was changing :P. You can ignore my request.
The free-format commands flow is a very nice feature!
