### ISSUE TITLE
It possible to use it only VThermo and Homey Heating Scheduler?

### ISSUE THREAD

**Issue by vampywiz17** [nlrb/com.tclcode.otgw#20]
Hello! 

I thinking that if i use a OpenTherm gateway without "physical" thermostat, only Homey virtual thermostat (VThermo) is able to work?

And the opentherm gateway able to modulate automatically if i send the requed datas? (internal, external temperature)  or it need to set the modulation manually?

If i want to simplificate the question. it possible to replace a smart thermostat (like Tado) for this one and other (VThermo, Homey Heating Scheduler) apps?

**Comment by nlrb** [comment]
I don't know the VThermo, so hard for me to comment. In principle it should be possible to not use a thermostat, but not recommended, see http://otgw.tclcode.com/standalone.html#external.
