### ISSUE TITLE
Remote override roomsetpoint not updated 

### ISSUE THREAD

**Issue by jtebbens** [nlrb/com.tclcode.otgw#23]
Hi after some testing with the otgw sensor I noticed this value not changing at all. When I apply a TC=19 it gets to roomset point but the override stays 0. Also the condition flow is acting weird on this and always says it’s overriden which does not make sense either. Currently I have no means/ways to detect if the OTGW is in control of the temperature or the thermostat. I expect an override to be non zero for override in your Homey OTGW app so I can use it as checks for sending a TC or TT=0 to get the themostat in control.

![4EAC9C6D-F3D5-437E-8097-0307A330D558](https://user-images.githubusercontent.com/18558267/153842879-79238deb-16c2-4a43-a6ab-9b7898485756.png)
![3BE7EC61-7E15-46AF-8969-C68AD2407CDE](https://user-images.githubusercontent.com/18558267/153842887-cd86aa86-d201-42ea-9909-4fbcc174ec75.png)

**Comment by nlrb** [comment]
Note that the app just is an interface to the OTG. So you will see the same behavior when using the OTG native app on PC. Note that not all thermostats handle the remote override the same way (or properly in my view, but unfortunately the spec is vague in this area). The override value you see should be whats comes back via the thermostat. What do you see in the logging?

**Comment by jtebbens** [comment]
Hi Ramon, thx for your time and feedback. I'be been investigating further and stumbled upon an issue with the OTGW firmware 4.2.5. This one seems to fail on override room set temperature in the first place. I've managed to upgrade the gateway to 5.2 which seems to have a fix for magid 9 and 100. 

Yet the condition check still is a problem. Thermostat is in charge, override room set temp is 0 yet still the test says override is active. 

![image](https://user-images.githubusercontent.com/18558267/153914792-12d3a55e-0a96-475f-b49c-cc319e4fdc81.png)

**Comment by nlrb** [comment]
The above condition is never evaluated since there is no trigger. You need to have an if statement that triggers the condition evaluation.

**Comment by nlrb** [comment]
Hint: use condition ‘overschrijven kamertemp. wordt’ actief/inactief.

**Comment by jtebbens** [comment]
Thx was about to ask how to evaluate such a condition as I seem to misinterpret the function of that condition. I was using variables before storing the TC values and checking if they would be non zero etc. Hence I figured the override functionality in OTGW itself was bogus. 

I will give your hint a shot to verify.

Thx again!

**Comment by jtebbens** [comment]
Will close issue, answer to the problem is fixed in firmware 5.2 of the gateway.
