### ISSUE TITLE
As per homey firmware 7.3.0 OpenTherm crashes

### ISSUE THREAD

**Issue by jtebbens** [nlrb/com.tclcode.otgw#24]
Memory goes sky high and app stops responding. I've sent a diagnostic report earlier.

Firmware upgrade done around 10am this morning.

![image](https://user-images.githubusercontent.com/18558267/156420140-ee5ae242-904a-43f4-af37-1b1f14766673.jpeg)

**Comment by nlrb** [comment]
Why do you raise an issue on the app when the behavior is related to the firmware?

**Comment by jtebbens** [comment]
Sorry I was more thinking that the firmware could negatively affect your app and suddenly increases memory for functions or methods used.

**Comment by jtebbens** [comment]
Fine I will raise it with Athom.
