### ISSUE TITLE
The app is not compatible / working on the new Homey Pro (Early 2023)

### ISSUE THREAD

**Issue by RonaldNeed** [nlrb/com.tclcode.otgw#27]
Hi Ramón,
Following the Homey website the OTGW-app is not compatible / working on a new Homey Pro (Early 2023). 
Is it possible to make the app working on it?
Regards, Ronald

**Comment by nlrb** [comment]
Hi Ronald,

Of course this should be possible. I'm just not spending time on it.

Grtz,
-Ramón

**Comment by alexm83** [comment]
Today we received the brand new Homey Pro (2023) and unfortunately Opentherm app does not work on it.

Do you still want to put time into solving it? 

Groeten Alex

**Comment by nlrb** [comment]
Test version 3.0.0 is available now.

**Comment by RonaldNeed** [comment]
Ramón, 
Thanks for spending time on it to create an OTGW version that works also on the Homey Pro (Early 2023). 
Regards, Ronald
