### ISSUE TITLE
Insights room setpoint

### ISSUE THREAD

**Issue by denniedegroot** [nlrb/com.tclcode.otgw#3]
In the OpenTherm Gateway settings I miss the option for "room setpoint" logging.
In the devices I can add a "room setpoint" which is correctly logging to insights but I would also like the option under the settings tab.

**Comment by nlrb** [comment]
Hmmm, yes, I was aware of this. But since you can still log it via a temperature device I thought I could get away with this. Let me see if I can add it anyway.

**Comment by denniedegroot** [comment]
Thanks!
