### ISSUE TITLE
Incompatible with Homey FW 0.9.1: invalid_capability_at_index_3

### ISSUE THREAD

**Issue by DieterKoblenz** [nlrb/com.tclcode.otgw#8]
After the FW upgrade my opentherm thermostat dissapeared. I tried to re-add it but the following message appeared:

invalid_capability_at_index_3

(Removing and installing the app again did not solve this)

**Comment by nlrb** [comment]
Correct. As stated in the FW upgrade notes, devices with custom capabilities will not work and be deleted with FW 0.9.1. The OTG thermostat device uses custom capabilities.

**Comment by DieterKoblenz** [comment]
Actually it only states it removes device with custom capabilities. It also says "Added support for custom capabilities" but I guess that requires code changes here?

**Comment by nlrb** [comment]
Yes, a code change is needed indeed.
