### ISSUE TITLE
Not really a otgw issue: Outside temp, accept string input

### ISSUE THREAD

**Issue by DieterKoblenz** [nlrb/com.tclcode.otgw#9]
Is it possible to input a string from for example Athom's Yahoo app or the Weather Underground app and convert it to a INTEGER inside the app? At the moment I can't really use this function as there are no apps that provide outside temperature input correctly.

**Comment by DieterKoblenz** [comment]
Actually I can not insert any variable including number ones.

**Comment by DieterKoblenz** [comment]
Just to be clear, I can not insert any token into the outside temp.

**Comment by nlrb** [comment]
Can you make an issue for Athom on this?

According to the docs it should be possible [(developer docs):](https://developers.athom.com/library/flow/arguments/)

> Number: Regular text input. Tokens can be dropped in this field as well.

However, you also cannot drop a token on e.g. the 'greater than' card.
